spring:
  application:
    name: model-registry-service
  datasource:
    url: ${MODEL_REGISTRY_DATABASE_URL:jdbc:postgresql://localhost:5432/autumn_wind}
    username: ${MODEL_REGISTRY_DATABASE_USERNAME:autumn_wind}
    password: ${MODEL_REGISTRY_DATABASE_PASSWORD}
  flyway:
    create-schemas: true
    default-schema: model_registry
    schemas: model_registry
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: model_registry
    open-in-view: false
  jackson:
    datatype:
      enum:
        fail-on-numbers-for-enums: true
    deserialization:
      accept-float-as-int: false
      fail-on-unknown-properties: true
    mapper:
      allow-coercion-of-scalars: false

server:
  port: ${MODEL_REGISTRY_SERVER_PORT:8083}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
