package io.github.yanhuo218.autumnwind.modelregistry.application.endpoint;

public enum ModelRegistryErrorCode {
    INVALID_REQUEST("AW-MODEL_REGISTRY-VALIDATION-0001"),
    INVALID_SERVICE_TOKEN("AW-MODEL_REGISTRY-AUTH-0001"),
    ACCESS_DENIED("AW-MODEL_REGISTRY-FORBIDDEN-0001"),
    ENDPOINT_NOT_FOUND("AW-MODEL_REGISTRY-NOT_FOUND-0001"),
    ENDPOINT_VERSION_CONFLICT("AW-MODEL_REGISTRY-CONFLICT-0001"),
    ENDPOINT_TEST_UNAVAILABLE("AW-MODEL_REGISTRY-CONFLICT-0005"),
    ENDPOINT_SECRET_FAILURE("AW-MODEL_REGISTRY-DEPENDENCY-0001"),
    MODEL_NOT_FOUND("AW-MODEL_REGISTRY-NOT_FOUND-0002"),
    MODEL_CONFLICT("AW-MODEL_REGISTRY-CONFLICT-0002"),
    DEFAULT_MODEL_CONFLICT("AW-MODEL_REGISTRY-CONFLICT-0003"),
    MODEL_VERSION_CONFLICT("AW-MODEL_REGISTRY-CONFLICT-0004"),
    INTERNAL_ERROR("AW-MODEL_REGISTRY-INTERNAL-0001");

    private final String value;

    ModelRegistryErrorCode(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }
}
